# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a988f4e3bf3df1e2e82dfe66e7269b420f40c2b7e15498acece60e31600325b15806509847a2daf43167ed9eb1843fa4972818bdf51cecebf3f06a7f7116ab34

test:
  secret_key_base: 8b79b8063093d7b31f7481a956cac088da04527d74ea02f09b3de57663cf7f994df04ac4c35f83c2cba59cb13c6637d9e8032f0da575160c50c857c192c603ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
